unit_dict = {
    "A1": "Department of Biology",
    "A2": "School of Computing",
    "A3": "Institute for Social Studies",
    "A4": "Centre for Data Science",
    "A5": "Department of Physics",
    "AJ": "Health Research Institute",
    "AK": "School of Engineering",
    "AL": "Department of History",
    "AN": "Department of Chemistry",
    "AS": "Department of Mathematics",
    "AU": "School of Medicine",
    "AV": "Institute of Technology",
    "AW": "School of Languages",
    "AZ": "Centre for Environmental Research",
    "B2": "Institute for Neuroscience",
    "B3": "Department of Education",
    "B5": "Faculty of Law",
    "B8": "Business School",
    "B9": "Institute of Global Health",
    "BB": "Centre for Humanities",
    "BH": "Research Strategy Office",
    "BQ": "Institute for Population Studies",
    "BR": "University Administration Office",
    "BS": "Graduate Training Centre",
    "BV": "School of Public Health",
    "BW": "Department of Economics",
    "BX": "Institute for Applied Statistics",
    "BZ": "School of Political Science",
    "C1": "Central Operations",
    "CC": "School of Life Sciences",
    "CF": "Centre for Advanced Medicine",
    "CJ": "Neuroscience Research Unit",
    "CM": "Institute for Pharmaceutical Research",
    "CN": "School of Psychology",
    "CQ": "Cognitive Science Centre",
    "CR": "School of Social Policy",
    "CS": "School of Humanities",
    "CW": "Innovation & Technology Hub",
    "E3": "Research Incubator",
    "EV": "Institute for International Studies",
    "GX": "School of Materials Science",
    "H2": "Centre for Molecular Biology",
    "H3": "Institute for Radiation Research",
    "H4": "Clinical Sciences Unit",
    "H5": "Genetics Research Centre",
    "H6": "Clinical Trials Unit",
    "H7": "Department of Endocrinology",
    "H8": "Institute for Molecular Medicine",
    "H9": "Structural Biology Centre",
    "HB": "Experimental Medicine Institute",
    "HC": "Vaccine Development Centre",
    "HE": "Department of Reproductive Health",
    "HF": "Orthopaedics and Trauma Research",
    "HI": "Epidemiology Unit",
    "HJ": "Surgical Research Centre",
    "HM": "Neuroscience Institute",
    "HN": "Paediatrics",
    "HP": "Cancer Research Centre",
    "HQ": "Department of Psychiatry",
    "HS": "Cardiovascular Research Institute",
    "HT": "Child Health Research Group",
    "JF": "Biomedical Services",
    "KZ": "Computational Sciences Institute",
    "PS": "Global Health Innovation Centre",
    "AC": "Department of Geography",
    "AE": "Department of Anthropology",
    "AF": "Institute for Environmental Studies",
    "BA": "Faculty of Law",
    "C0": "Social Sciences Division",
    "CE": "Centre for Social Data",
    "CT": "Politics and Governance Institute",
    "CU": "Department of Economics",
    "CV": "School of Social Policy",
    "CX": "Centre for Legal Studies",
    "CY": "Department of Sociology",
    "CZ": "Institute for Digital Society",
    "D3": "Social Sciences HQ",
    "EB": "Institute of Archaeology",
    "EC": "Archaeological Research Centre",
    "EP": "Department of Education",
    "JG": "Centre for Criminology",
    "JQ": "Transport Studies Institute",
    "LC": "Future Studies Institute",
    "LD": "Sustainability Research School",
    "LE": "School of Public Policy",
    "M3": "Centre for Area Studies",
    "MQ": "Business School",
    "VG": "Department of Development Studies",
    "AM": "School of Statistics",
    "AP": "Department of Plant Sciences",
    "AT": "Department of Zoology",
    "BK": "School of Mathematics",
    "BL": "School of Computer Science",
    "CB": "Department of Biology",
    "D4": "Physical and Life Sciences Division",
    "DB": "Astrophysics Research Group",
    "DC": "Atmospheric Physics Department",
    "DD": "Doctoral Training Centre (Science)",
    "DF": "Department of Engineering",
    "DG": "School of Earth Sciences",
    "DH": "Department of Chemistry",
    "DJ": "Materials Science Department",
    "DK": "Department of Physics",
    "DL": "Particle Physics Group",
    "DM": "Organic Chemistry Group",
    "DN": "Physical Chemistry Department",
    "DP": "School of Chemistry",
    "DQ": "Chemical Biology Research Centre",
    "DR": "Theoretical Physics Unit",
    "DS": "Research Park Directorate",
    "DT": "Central Physics Department",
    "DU": "Institute for Laser Physics",
    "DW": "Chemistry Research Labs",
    "E4": "Energy Research Institute",
    "E9": "e-Research Centre",
    "LA": "Financial Analytics Institute",
    "AX": "Faculty of English",
    "BE": "Faculty of Classics",
    "CA": "Faculty of Languages",
    "CD": "Faculty of History",
    "CG": "Faculty of Music",
    "CK": "Faculty of Asian Studies",
    "DX": "Faculty of Theology",
    "E0": "Humanities Division",
    "E1": "Department of Linguistics",
    "GP": "School of Art",
    "M1": "American Studies Institute",
    "VF": "Humanities Research Foundation",
    "YD": "Faculty of Philosophy",
    "YS": "Institute for Ethics",
    "EQ": "Continuing Education (HQ)",
    "XA": "Continuing Education (International)",
    "XB": "Continuing Education (Professional)",
    "XD": "Continuing Education (Distance Learning)",
    "XF": "Continuing Education (Residential)",
    "XG": "Continuing Education (Community)",
    "XJ": "Foundation Year Programme",
    "XK": "Language Centre",
    "AB": "Museum of Anthropology",
    "ED": "Art Museum",
    "ET": "Museum of Science",
    "EW": "Museum of Natural History",
    "F0": "Academic Services Division",
    "F5": "Finance and Administration",
    "F7": "Communications Office",
    "F8": "Assessment Centre",
    "FA": "Library Services",
    "FC": "Social Sciences Library",
    "FJ": "Innovation Enterprise Office",
    "FK": "Humanities Library",
    "FP": "Science Library",
    "FS": "Student Services",
    "FW": "Special Collections Library",
    "FZ": "Digital Library Systems",
    "GC": "Botanical Garden",
    "E2": "IT Services",
    "GB": "Careers Office",
    "GD": "Sports Department",
    "GL": "Governance Office",
    "GT": "Student Welfare Office",
    "GU": "Student Clubs Committee",
    "GY": "Health & Safety Office",
    "GZ": "Occupational Health Service",
    "J1": "Council Secretariat",
    "J3": "Graduate Admissions",
    "J4": "Divisional Offices",
    "J6": "Education Policy Unit",
    "J9": "Student Administration",
    "JB": "Assurance Office",
    "JC": "Community Club",
    "JZ": "Research Focus Unit",
    "K3": "Teaching and Learning Centre",
    "K8": "Planning and Resources Office",
    "K9": "Examinations Office",
    "KA": "Registrar’s Office",
    "KB": "Public Affairs Directorate",
    "KC": "Research Services",
    "KD": "Alumni Office",
    "KF": "Human Resources",
    "KH": "Finance",
    "KK": "Child Care Services",
    "KM": "Vice-Chancellor’s Office",
    "KN": "Legal Services",
    "KQ": "Student Fees and Funding",
    "KR": "Development Office",
    "KS": "International Engagement Office",
    "KT": "Staffing Services",
    "KX": "Student Systems",
    "L4": "External Affairs Directorate",
    "SZ": "Admissions and Outreach",
    "VA": "Language Centre",
    "VH": "Economics Programme",
    "GH": "University Theatre",
    "GM": "University Club",
    "JW": "Estates Services",
    "ZB": "Investment Office",
    "GR": "College of Social Studies",
    "GS": "College of Natural Sciences",
    "JT": "General Revenue Account",
    "LB": "Institute for Ageing",
    "S1": "New College",
    "TA": "Scholarship Programmes",
    "V1": "Financial Adjustments",
    "V4": "Teaching Support Unit",
    "V6": "International Centre (Beijing)",
    "V8": "Vaccine Research Foundation",
    "VC": "Student Union",
    "VD": "Humanities Foundation",
    "VJ": "Student Financial Aid",
    "VL": "Learning Foundation",
    "VO": "Science and Engineering Trust",
    "VP": "Cancer Research Trust",
    "VR": "Global Research Trust",
    "VU": "Endowment Office",
    "VW": "University Enterprises Ltd",
    "VX": "University Innovation Ltd",
    "VY": "Technology Transfer Ltd",
    "X1": "University Mutual Ltd",
    "ZE": "University Development Trust",
}
